[package]
name = "contracts"
version = "0.1.0"

[dependencies]
starknet = "2.7.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.27.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "98aadc7e3f12dbb026e853604fe2cc061451cc8a" }
# ekubo = { git = "https://github.com/EkuboProtocol/abis", rev = "ef7a4076209317bb677846acd3590d990f2ae5a8" }

[[target.starknet-contract]]
casm = true
sierra = true
allowed-libfuncs-list.name = "experimental"

[tool.fmt]
sort-module-level-items = false

[tool.snforge]
exit_first = false


[cairo]
sierra-replace-ids = true

[lib]
name = "contracts"